// <auto-generated />
using System;
using Integration.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Integration.Shared.Persistence.Migrations
{
    [DbContext(typeof(LabDbContext))]
    partial class LabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.ExportRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("RequestId");

                    b.ToTable("ExportRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExportRequests_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_ExportRequests_Currency", "[Currency] = 'TRY'");

                            t.HasCheckConstraint("CK_ExportRequests_Reference", "LEN([ExternalReference]) BETWEEN 1 AND 80");
                        });
                });

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.InboxReceipt", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TransportMessageId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IntegrationJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ConsumerName", "TransportMessageId");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_InboxReceipts_EventId");

                    b.HasIndex("IntegrationJobId");

                    b.ToTable("InboxReceipts", (string)null);
                });

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.IntegrationJob", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptsStarted")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalReceiptId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("RequestId");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("IX_IntegrationJobs_Dispatch");

                    b.ToTable("IntegrationJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntegrationJobs_Attempts", "[AttemptsStarted] >= 0");

                            t.HasCheckConstraint("CK_IntegrationJobs_CompletedHasReceipt", "([Status] <> 'Completed') OR ([ExternalReceiptId] IS NOT NULL AND [CompletedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_IntegrationJobs_Status", "[Status] IN ('Pending', 'Processing', 'RetryScheduled', 'Completed', 'DeadLetterPending', 'DeadLettered')");
                        });
                });

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.JobAttempt", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("SafeErrorCode")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RequestId", "AttemptNumber");

                    b.ToTable("JobAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_JobAttempts_Outcome", "[Outcome] IN ('Started', 'Succeeded', 'TransientFailure', 'PermanentFailure', 'Abandoned')");
                        });
                });

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RejectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("SourceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("RejectionId")
                        .IsUnique()
                        .HasDatabaseName("UX_OutboxMessages_DeadLetter_PerRejection")
                        .HasFilter("[RejectionId] IS NOT NULL");

                    b.HasIndex("SourceRequestId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("UX_OutboxMessages_SourceRequest_Kind")
                        .HasFilter("[SourceRequestId] IS NOT NULL");

                    b.HasIndex("Status", "NextAttemptAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_Dispatch");

                    b.ToTable("OutboxMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutboxMessages_Kind", "[Kind] IN ('Export', 'DeadLetter')");

                            t.HasCheckConstraint("CK_OutboxMessages_Links", "([Kind] = 'Export' AND [SourceRequestId] IS NOT NULL AND [RejectionId] IS NULL) OR ([Kind] = 'DeadLetter' AND (([SourceRequestId] IS NOT NULL AND [RejectionId] IS NULL) OR ([SourceRequestId] IS NULL AND [RejectionId] IS NOT NULL)))");

                            t.HasCheckConstraint("CK_OutboxMessages_PublishedHasTimestamp", "([Status] <> 'Published') OR ([PublishedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_OutboxMessages_Status", "[Status] IN ('Pending', 'Publishing', 'Published')");
                        });
                });

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.RejectedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BodyLength")
                        .HasColumnType("int");

                    b.Property<string>("BodySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("DeadLetterPublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .IsUnicode(false)
                        .HasColumnType("varchar(48)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TransportMessageId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("UX_RejectedMessages_Fingerprint");

                    b.ToTable("RejectedMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_RejectedMessages_BodyLength", "[BodyLength] >= 0");
                        });
                });

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.InboxReceipt", b =>
                {
                    b.HasOne("Integration.Shared.Persistence.Entities.IntegrationJob", null)
                        .WithMany()
                        .HasForeignKey("IntegrationJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.IntegrationJob", b =>
                {
                    b.HasOne("Integration.Shared.Persistence.Entities.ExportRecord", null)
                        .WithOne()
                        .HasForeignKey("Integration.Shared.Persistence.Entities.IntegrationJob", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.JobAttempt", b =>
                {
                    b.HasOne("Integration.Shared.Persistence.Entities.IntegrationJob", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Integration.Shared.Persistence.Entities.OutboxMessage", b =>
                {
                    b.HasOne("Integration.Shared.Persistence.Entities.RejectedMessage", null)
                        .WithMany()
                        .HasForeignKey("RejectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Integration.Shared.Persistence.Entities.ExportRecord", null)
                        .WithMany()
                        .HasForeignKey("SourceRequestId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
