// <auto-generated />
using System;
using FakeErp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeErp.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    [Migration("20260910205330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FakeErp.AppliedExport", b =>
                {
                    b.Property<string>("OperationKey")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("ExternalReceiptId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("OperationKey");

                    b.HasIndex("ExternalReceiptId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppliedExports_Receipt");

                    b.HasIndex("ExternalReference")
                        .HasDatabaseName("IX_AppliedExports_Reference");

                    b.ToTable("AppliedExports", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppliedExports_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_AppliedExports_Currency", "[Currency] = 'TRY'");

                            t.HasCheckConstraint("CK_AppliedExports_Reference", "LEN([ExternalReference]) BETWEEN 1 AND 80");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
